CREATE TABLE PERSON(
	P# char(10) PRIMARY KEY,
	PName char(10),
	PAge bigint CHECK(PAge>18)
)
CREATE TABLE ROOM(
	R# char(10) PRIMARY KEY,
	RName char(10),
	RArea bigint
)
CREATE TABLE PR(
	Date datetime,
	P# char(10),
	R# char(10),
	FOREIGN KEY(P#) REFERENCES PERSON(P#),
	FOREIGN KEY(R#) REFERENCES ROOM(R#),
)

ALTER TABLE PERSON
ADD PType char(10)

ALTER TABLE PERSON
DROP CONSTRAINT CK__PERSON__PAge__36B12243

ALTER TABLE ROOM
ALTER COLUMN RName char(40)



ALTER TABLE ROOM
DROP COLUMN RArea



ALTER TABLE PR
DROP CONSTRAINT FK__PR__P#__3A81B327
ALTER TABLE PR
DROP CONSTRAINT FK__PR__R#__3B75D760


CREATE INDEX RINDEX ON ROOM(R# DESC)
CREATE INDEX PINDEX ON PERSON(P# ASC)

CREATE UNIQUE INDEX PNINDEX ON PERSON(PNAME ASC)

DROP INDEX PINDEX ON PERSON